-- SQL dump generated by Copilot DB Exporter
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

-- Table: ASP_activity_logs
CREATE TABLE "ASP_activity_logs" (
	id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	action VARCHAR(100) NOT NULL, 
	description TEXT, 
	ip_address VARCHAR(45), 
	user_agent TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES "ASP_users" (id)
);

-- Table: ASP_agencies
CREATE TABLE "ASP_agencies" (
	id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	code VARCHAR(20) NOT NULL, 
	address TEXT, 
	phone VARCHAR(20), 
	email VARCHAR(120), 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (code)
);

-- Table: ASP_categories
CREATE TABLE "ASP_categories" (
	id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	description TEXT, 
	agency_id INTEGER NOT NULL, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id)
);

-- Table: ASP_customers
CREATE TABLE "ASP_customers" (
	id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	email VARCHAR(120), 
	phone VARCHAR(20), 
	address TEXT, 
	city VARCHAR(50), 
	state VARCHAR(50), 
	pincode VARCHAR(10), 
	gst_number VARCHAR(20), 
	credit_limit NUMERIC(10, 2), 
	credit_period INTEGER, 
	location_id INTEGER NOT NULL, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(location_id) REFERENCES "ASP_locations" (id)
);

-- Table: ASP_indian_tax_codes
CREATE TABLE "ASP_indian_tax_codes" (
	id INTEGER NOT NULL, 
	code VARCHAR(20) NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	rate NUMERIC(5, 2) NOT NULL, 
	description TEXT, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (code)
);

-- Table: ASP_inventory_transactions
CREATE TABLE "ASP_inventory_transactions" (
	id INTEGER NOT NULL, 
	product_id INTEGER NOT NULL, 
	transaction_type VARCHAR(20) NOT NULL, 
	quantity_change INTEGER NOT NULL, 
	quantity_before INTEGER NOT NULL, 
	quantity_after INTEGER NOT NULL, 
	unit_cost NUMERIC(10, 2), 
	reference_id INTEGER, 
	reference_type VARCHAR(20), 
	notes TEXT, 
	created_by INTEGER NOT NULL, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(product_id) REFERENCES "ASP_products" (id), 
	FOREIGN KEY(created_by) REFERENCES "ASP_users" (id)
);

-- Table: ASP_invoices
CREATE TABLE "ASP_invoices" (
	id INTEGER NOT NULL, 
	invoice_number VARCHAR(50) NOT NULL, 
	order_id INTEGER NOT NULL, 
	agency_id INTEGER NOT NULL, 
	customer_id INTEGER NOT NULL, 
	subtotal NUMERIC(10, 2) NOT NULL, 
	tax_amount NUMERIC(10, 2), 
	discount_amount NUMERIC(10, 2), 
	total_amount NUMERIC(10, 2) NOT NULL, 
	status VARCHAR(20), 
	issue_date DATETIME, 
	due_date DATETIME, 
	payment_terms VARCHAR(100), 
	notes TEXT, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (invoice_number), 
	FOREIGN KEY(order_id) REFERENCES "ASP_orders" (id), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id), 
	FOREIGN KEY(customer_id) REFERENCES "ASP_customers" (id)
);

-- Table: ASP_locations
CREATE TABLE "ASP_locations" (
	id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	address TEXT, 
	city VARCHAR(50), 
	state VARCHAR(50), 
	zip_code VARCHAR(10), 
	phone VARCHAR(20), 
	agency_id INTEGER NOT NULL, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id)
);

-- Table: ASP_low_stock_alerts
CREATE TABLE "ASP_low_stock_alerts" (
	id INTEGER NOT NULL, 
	product_id INTEGER NOT NULL, 
	threshold_quantity INTEGER NOT NULL, 
	current_quantity INTEGER NOT NULL, 
	status VARCHAR(20), 
	alerted_at DATETIME, 
	resolved_at DATETIME, 
	resolved_by INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(product_id) REFERENCES "ASP_products" (id), 
	FOREIGN KEY(resolved_by) REFERENCES "ASP_users" (id)
);

-- Table: ASP_order_items
CREATE TABLE "ASP_order_items" (
	id INTEGER NOT NULL, 
	order_id INTEGER NOT NULL, 
	product_id INTEGER NOT NULL, 
	quantity INTEGER NOT NULL, 
	uom VARCHAR(20), 
	unit_price NUMERIC(10, 2) NOT NULL, 
	mrp_price NUMERIC(10, 2) NOT NULL, 
	discount_percentage NUMERIC(5, 2), 
	discounted_price NUMERIC(10, 2) NOT NULL, 
	tax_code VARCHAR(20), 
	tax_rate NUMERIC(5, 2), 
	tax_amount NUMERIC(10, 2), 
	line_total NUMERIC(10, 2) NOT NULL, 
	total_price NUMERIC(10, 2) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(order_id) REFERENCES "ASP_orders" (id), 
	FOREIGN KEY(product_id) REFERENCES "ASP_products" (id)
);

-- Table: ASP_orders
CREATE TABLE "ASP_orders" (
	id INTEGER NOT NULL, 
	order_number VARCHAR(50) NOT NULL, 
	customer_id INTEGER NOT NULL, 
	agency_id INTEGER NOT NULL, 
	salesperson_id INTEGER NOT NULL, 
	status VARCHAR(20), 
	payment_status VARCHAR(20), 
	total_amount NUMERIC(10, 2), 
	subtotal_amount NUMERIC(10, 2), 
	total_tax_amount NUMERIC(10, 2), 
	total_items_count INTEGER, 
	discount NUMERIC(10, 2), 
	tax NUMERIC(10, 2), 
	notes TEXT, 
	order_date DATETIME, 
	delivery_date DATETIME, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (order_number), 
	FOREIGN KEY(customer_id) REFERENCES "ASP_customers" (id), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id), 
	FOREIGN KEY(salesperson_id) REFERENCES "ASP_users" (id)
);

-- Table: ASP_payment_methods
CREATE TABLE "ASP_payment_methods" (
	id INTEGER NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	code VARCHAR(20) NOT NULL, 
	is_active BOOLEAN, 
	agency_id INTEGER NOT NULL, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (code), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id)
);

-- Table: ASP_payments
CREATE TABLE "ASP_payments" (
	id INTEGER NOT NULL, 
	payment_number VARCHAR(50) NOT NULL, 
	invoice_id INTEGER NOT NULL, 
	payment_method_id INTEGER NOT NULL, 
	amount NUMERIC(10, 2) NOT NULL, 
	payment_date DATETIME, 
	transaction_id VARCHAR(100), 
	status VARCHAR(20), 
	notes TEXT, 
	processed_by INTEGER NOT NULL, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (payment_number), 
	FOREIGN KEY(invoice_id) REFERENCES "ASP_invoices" (id), 
	FOREIGN KEY(payment_method_id) REFERENCES "ASP_payment_methods" (id), 
	FOREIGN KEY(processed_by) REFERENCES "ASP_users" (id)
);

-- Table: ASP_products
CREATE TABLE "ASP_products" (
	id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	description TEXT, 
	sku VARCHAR(50) NOT NULL, 
	price NUMERIC(10, 2), 
	cost NUMERIC(10, 2), 
	stock_quantity INTEGER, 
	category VARCHAR(100), 
	uom VARCHAR(20), 
	tax_rate NUMERIC(5, 2), 
	tax_code VARCHAR(20), 
	buy_price NUMERIC(10, 2), 
	sell_price NUMERIC(10, 2), 
	mrp_price NUMERIC(10, 2), 
	margin NUMERIC(5, 2), 
	category_id INTEGER, 
	uom_id INTEGER, 
	tax_master_id INTEGER, 
	agency_id INTEGER NOT NULL, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (sku), 
	FOREIGN KEY(category_id) REFERENCES "ASP_categories" (id), 
	FOREIGN KEY(uom_id) REFERENCES "ASP_uoms" (id), 
	FOREIGN KEY(tax_master_id) REFERENCES "ASP_tax_masters" (id), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id)
);

-- Table: ASP_purchase_order_items
CREATE TABLE "ASP_purchase_order_items" (
	id INTEGER NOT NULL, 
	po_id INTEGER NOT NULL, 
	product_id INTEGER NOT NULL, 
	quantity_ordered INTEGER NOT NULL, 
	quantity_received INTEGER, 
	unit_cost NUMERIC(10, 2) NOT NULL, 
	total_cost NUMERIC(10, 2) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(po_id) REFERENCES "ASP_purchase_orders" (id), 
	FOREIGN KEY(product_id) REFERENCES "ASP_products" (id)
);

-- Table: ASP_purchase_orders
CREATE TABLE "ASP_purchase_orders" (
	id INTEGER NOT NULL, 
	po_number VARCHAR(50) NOT NULL, 
	supplier_id INTEGER NOT NULL, 
	agency_id INTEGER NOT NULL, 
	total_amount NUMERIC(10, 2), 
	status VARCHAR(20), 
	order_date DATETIME, 
	expected_delivery DATETIME, 
	received_date DATETIME, 
	notes TEXT, 
	created_by INTEGER NOT NULL, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (po_number), 
	FOREIGN KEY(supplier_id) REFERENCES "ASP_suppliers" (id), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id), 
	FOREIGN KEY(created_by) REFERENCES "ASP_users" (id)
);

-- Table: ASP_stock_adjustment_items
CREATE TABLE "ASP_stock_adjustment_items" (
	id INTEGER NOT NULL, 
	adjustment_id INTEGER NOT NULL, 
	product_id INTEGER NOT NULL, 
	quantity_before INTEGER NOT NULL, 
	quantity_change INTEGER NOT NULL, 
	quantity_after INTEGER NOT NULL, 
	reason VARCHAR(200), 
	PRIMARY KEY (id), 
	FOREIGN KEY(adjustment_id) REFERENCES "ASP_stock_adjustments" (id), 
	FOREIGN KEY(product_id) REFERENCES "ASP_products" (id)
);

-- Table: ASP_stock_adjustments
CREATE TABLE "ASP_stock_adjustments" (
	id INTEGER NOT NULL, 
	adjustment_number VARCHAR(50) NOT NULL, 
	agency_id INTEGER NOT NULL, 
	reason VARCHAR(100) NOT NULL, 
	notes TEXT, 
	created_by INTEGER NOT NULL, 
	approved_by INTEGER, 
	status VARCHAR(20), 
	created_at DATETIME, 
	approved_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (adjustment_number), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id), 
	FOREIGN KEY(created_by) REFERENCES "ASP_users" (id), 
	FOREIGN KEY(approved_by) REFERENCES "ASP_users" (id)
);

-- Table: ASP_suppliers
CREATE TABLE "ASP_suppliers" (
	id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	contact_person VARCHAR(100), 
	email VARCHAR(120), 
	phone VARCHAR(20), 
	address TEXT, 
	agency_id INTEGER NOT NULL, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id)
);

-- Table: ASP_tax_masters
CREATE TABLE "ASP_tax_masters" (
	id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	tax_code VARCHAR(20) NOT NULL, 
	tax_rate NUMERIC(5, 2) NOT NULL, 
	description TEXT, 
	agency_id INTEGER NOT NULL, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (tax_code), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id)
);

-- Table: ASP_tax_rules
CREATE TABLE "ASP_tax_rules" (
	id INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	rate NUMERIC(5, 4) NOT NULL, 
	location_id INTEGER NOT NULL, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(location_id) REFERENCES "ASP_locations" (id)
);

-- Table: ASP_uoms
CREATE TABLE "ASP_uoms" (
	id INTEGER NOT NULL, 
	name VARCHAR(50) NOT NULL, 
	short_name VARCHAR(10) NOT NULL, 
	description TEXT, 
	agency_id INTEGER NOT NULL, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id)
);

-- Table: ASP_users
CREATE TABLE "ASP_users" (
	id INTEGER NOT NULL, 
	username VARCHAR(80) NOT NULL, 
	email VARCHAR(120) NOT NULL, 
	password_hash VARCHAR(256) NOT NULL, 
	first_name VARCHAR(50), 
	last_name VARCHAR(50), 
	role VARCHAR(20) NOT NULL, 
	agency_id INTEGER, 
	is_active BOOLEAN, 
	created_at DATETIME, 
	last_login DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (username), 
	UNIQUE (email), 
	FOREIGN KEY(agency_id) REFERENCES "ASP_agencies" (id)
);
COMMIT;
